#!/usr/bin/env bash
# bootstrap/verify.sh — smoke-tests every component.
# Exits 0 if all checks pass, 1 otherwise.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

MODE="installed"
case "${1:-}" in
  --fresh-clone)
    MODE="fresh-clone"
    ;;
  -h|--help)
    cat <<'EOF'
Usage: ./bootstrap/verify.sh [--fresh-clone]

Checks source layout, tool availability, and stack doctors.

Modes:
  default        Verify an installed RDS checkout, including generated local
                 install-state files such as .env and .rds-installed.
  --fresh-clone  Verify a clean source checkout before install. Generated
                 install-state files are reported as skipped, not failures.
EOF
    exit 0
    ;;
  "")
    ;;
  *)
    echo "FATAL: unknown argument: $1" >&2
    exit 2
    ;;
esac

FAIL=0
check() {
  local name="$1"; shift
  if "$@" >/dev/null 2>&1; then
    echo "✓ $name"
  else
    echo "✗ $name"
    FAIL=1
  fi
}

skip() {
  local name="$1"
  local reason="$2"
  echo "· $name ($reason)"
}

check "git"             git --version
check "ruby"            ruby --version
check "bundler"         bundle --version
check "psql"            psql --version
check "pg_isready"      pg_isready
check "curl"            curl --version
check "jq"              jq --version
check "rsync"           rsync --version
check "claude CLI"      claude --version
if command -v arnold >/dev/null 2>&1; then
  check "arnold CLI"      arnold --version
else
  skip "arnold CLI" "optional Wiki context helper not installed"
fi

check "scaffold dir"    test -f vendor/scaffold/scaffold.sh
check "wiki plugin"     test -f vendor/wiki/.claude-plugin/plugin.json
check "rails starter"  test -f vendor/rails-starter/bin/template-setup

check "AGENT.md"        test -f AGENT.md
check "bin/rds-build"   test -x bin/rds-build
check "bin/rds-intake"  test -x bin/rds-intake
check "bin/rds-spec"    test -x bin/rds-spec
check "bin/rds-deploy"  test -x bin/rds-deploy
check "bin/rds-status"  test -x bin/rds-status
check "bin/rds-clone-repo" test -x bin/rds-clone-repo
check "bin/rds-rails-init" test -x bin/rds-rails-init
check "bin/rds-start"      test -x bin/rds-start
check "bin/rds-stop"       test -x bin/rds-stop
check "bin/rds-event"      test -x bin/rds-event
check "bin/rds-notify"     test -x bin/rds-notify
check "bin/rds-fix"        test -x bin/rds-fix
check "bin/rds-chat"       test -x bin/rds-chat
check "bin/rds-dashboard"  test -x bin/rds-dashboard
check "bin/rds-watchdog"   test -x bin/rds-watchdog
check "dashboard/src/server.ts" test -f dashboard/src/server.ts
check "dashboard/package.json"  test -f dashboard/package.json
check "dashboard/public/ansi_up.min.js" test -f dashboard/public/ansi_up.min.js
check "bin/lib/common.sh"  test -f bin/lib/common.sh
check "bin/lib/state.sh"   test -f bin/lib/state.sh
check "bin/lib/logging.sh" test -f bin/lib/logging.sh
check "stacks/registry.yml" test -f stacks/registry.yml
check "skills/registry.json" test -f skills/registry.json

if [[ "$MODE" == "fresh-clone" ]]; then
  skip ".env" "generated by install/runtime"
  skip ".rds-installed" "generated by bootstrap/install.sh"
else
  check ".env"            test -f .env
  check ".rds-installed"  test -f .rds-installed
fi

# --- Per-stack doctors ------------------------------------------------------
# Every stack with stacks/<id>/doctor.sh contributes its own prereq checks.
# Failures bubble up via the shared FAIL counter.
shopt -s nullglob
for manifest in stacks/*/manifest.json; do
  id="$(basename "$(dirname "$manifest")")"
  doctor_rel="$(jq -r '.doctor // ""' "$manifest" 2>/dev/null || echo "")"
  if [[ -n "$doctor_rel" && -x "$ROOT/$doctor_rel" ]]; then
    echo "--- stack:$id doctor ---"
    check "stack:$id stack.yaml" test -f "$ROOT/stacks/$id/stack.yaml"
    if "$ROOT/$doctor_rel"; then
      :  # stack-doctor prints its own ✓ lines
    else
      FAIL=1
    fi
  else
    check "stack:$id stack.yaml" test -f "$ROOT/stacks/$id/stack.yaml"
    echo "· stack:$id (no doctor.sh)"
  fi
done
shopt -u nullglob

echo
if [[ "$FAIL" -eq 0 ]]; then
  echo "All checks passed."
else
  echo "One or more checks failed. See docs/TROUBLESHOOTING.md."
fi

exit "$FAIL"
