#!/usr/bin/env bash
set -euo pipefail

APP_NAME="${1:-rds_astro_site}"
APP_DEST="${2:?app destination required}"

slug="$(printf '%s' "$APP_NAME" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g')"
[[ -n "$slug" ]] || slug="rds-astro-site"

mkdir -p "$APP_DEST/src/pages" "$APP_DEST/src/layouts" "$APP_DEST/src/components" "$APP_DEST/public" "$APP_DEST/tmp/pids" "$APP_DEST/log"

cat > "$APP_DEST/package.json" <<JSON
{
  "name": "${slug}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "test": "astro check || astro build"
  },
  "dependencies": {
    "astro": "latest",
    "@astrojs/check": "latest",
    "typescript": "latest"
  },
  "devDependencies": {}
}
JSON

cat > "$APP_DEST/astro.config.mjs" <<'JS'
import { defineConfig } from "astro/config";

export default defineConfig({
  server: {
    host: "0.0.0.0",
  },
});
JS

cat > "$APP_DEST/tsconfig.json" <<'JSON'
{
  "extends": "astro/tsconfigs/strict"
}
JSON

cat > "$APP_DEST/src/layouts/BaseLayout.astro" <<'ASTRO'
---
const { title = "RDS Astro Site", description = "Astro thin web starter generated by RDS." } = Astro.props;
---
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content={description} />
    <title>{title}</title>
  </head>
  <body>
    <slot />
  </body>
</html>
<style is:global>
  :root {
    color: #101820;
    background: #f7fafc;
    font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }
  * { box-sizing: border-box; }
  body { margin: 0; min-width: 320px; min-height: 100vh; }
  main { min-height: 100vh; display: grid; place-items: center; padding: 32px; }
  section { width: min(760px, 100%); }
  .eyebrow { color: #0f766e; font-size: 12px; font-weight: 800; text-transform: uppercase; }
  h1 { margin: 0; font-size: clamp(40px, 8vw, 84px); line-height: 0.95; }
  p { color: #526070; font-size: 18px; line-height: 1.55; }
</style>
ASTRO

cat > "$APP_DEST/src/pages/index.astro" <<'ASTRO'
---
import BaseLayout from "../layouts/BaseLayout.astro";
---
<BaseLayout>
  <main>
    <section>
      <p class="eyebrow">RDS Astro stack</p>
      <h1>Ready for implementation</h1>
      <p>This Astro starter is wired for Zo preview, static pages, and content-led product work.</p>
    </section>
  </main>
</BaseLayout>
ASTRO

cat > "$APP_DEST/src/pages/health.json.ts" <<'TS'
export function GET() {
  return new Response(JSON.stringify({ ok: true, stack: "astro-thin-web" }), {
    headers: { "content-type": "application/json" },
  });
}
TS

cat > "$APP_DEST/.gitignore" <<'EOF'
node_modules
dist
.astro
.env
tmp/pids
log
EOF

cat > "$APP_DEST/AGENTS.md" <<'MD'
# RDS Astro Build Notes

- Keep this as an Astro project.
- Preserve `/health.json`; RDS uses it for local and public health checks.
- Use Astro pages/layouts first; add client islands only when interaction requires them.
- Generated product work should replace the starter UI, not the stack plumbing.
MD
