#!/usr/bin/env bash
set -euo pipefail

APP_NAME="${1:-rds_nextjs_app}"
APP_DEST="${2:?app destination required}"

slug="$(printf '%s' "$APP_NAME" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g')"
[[ -n "$slug" ]] || slug="rds-nextjs-app"

mkdir -p "$APP_DEST/app/api/health" "$APP_DEST/app/dashboard" "$APP_DEST/components" "$APP_DEST/lib" "$APP_DEST/tmp/pids" "$APP_DEST/log"

cat > "$APP_DEST/package.json" <<JSON
{
  "name": "${slug}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "typecheck": "tsc --noEmit",
    "test": "bun run typecheck"
  },
  "dependencies": {
    "next": "latest",
    "react": "latest",
    "react-dom": "latest",
    "lucide-react": "latest"
  },
  "devDependencies": {
    "@types/node": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "typescript": "latest"
  }
}
JSON

cat > "$APP_DEST/next.config.ts" <<'TS'
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "standalone",
};

export default nextConfig;
TS

cat > "$APP_DEST/tsconfig.json" <<'JSON'
{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "es2022"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
JSON

cat > "$APP_DEST/next-env.d.ts" <<'TS'
/// <reference types="next" />
/// <reference types="next/image-types/global" />
TS

cat > "$APP_DEST/app/layout.tsx" <<'TSX'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "RDS Next.js App",
  description: "Next.js full-stack starter generated by RDS.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
TSX

cat > "$APP_DEST/app/page.tsx" <<'TSX'
import Link from "next/link";
import { ReviewReadiness } from "@/components/review-readiness";

export default function Home() {
  return (
    <main className="shell">
      <section className="panel">
        <p className="eyebrow">RDS Next.js stack</p>
        <h1>Ready for implementation</h1>
        <p>
          This App Router starter is wired for Zo preview, a health endpoint,
          and Scaffold-driven product work.
        </p>
        <Link href="/dashboard">Open dashboard starter</Link>
      </section>
      <ReviewReadiness surface="public" />
    </main>
  );
}
TSX

cat > "$APP_DEST/app/dashboard/page.tsx" <<'TSX'
import { ReviewReadiness } from "@/components/review-readiness";

export default function DashboardPage() {
  return (
    <main className="shell">
      <section className="panel">
        <p className="eyebrow">Dashboard</p>
        <h1>Build surface</h1>
        <p>Scaffold tasks replace this starter with the product workflow.</p>
      </section>
      <ReviewReadiness surface="authenticated" />
    </main>
  );
}
TSX

cat > "$APP_DEST/components/review-readiness.tsx" <<'TSX'
type ReviewReadinessProps = {
  surface: "public" | "authenticated";
};

const items = [
  ["Works now", "Starter shell, navigation, and health endpoint are wired."],
  ["Seeded/sample", "Feature data is sample-only until product tasks replace this panel."],
  ["Stubbed/missing", "Production integrations, credentials, and PRD-specific workflows are not connected yet."],
  ["Review access", "Add seeded review credentials here when authentication is introduced."],
] as const;

export function ReviewReadiness({ surface }: ReviewReadinessProps) {
  return (
    <section className="readiness-panel" aria-labelledby="review-readiness-title">
      <p className="eyebrow">Review mode</p>
      <h2 id="review-readiness-title">What is real right now</h2>
      <div className="readiness-grid">
        {items.map(([label, value]) => (
          <article key={label}>
            <h3>{label}</h3>
            <p>{value}</p>
          </article>
        ))}
      </div>
      <p className="readiness-note">
        {surface === "public"
          ? "Public preview disclosure: this build is not production-ready until RDS evidence passes."
          : "Operator disclosure: keep this panel current as seeded, stubbed, or missing workflows change."}
      </p>
    </section>
  );
}
TSX

cat > "$APP_DEST/app/api/health/route.ts" <<'TS'
export function GET() {
  return Response.json({ ok: true, stack: "nextjs-fullstack" });
}
TS

cat > "$APP_DEST/app/globals.css" <<'CSS'
:root {
  color: #eef3f8;
  background: #0d1117;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

* { box-sizing: border-box; }
body { margin: 0; min-width: 320px; min-height: 100vh; }
.shell { min-height: 100vh; display: grid; gap: 28px; align-content: center; justify-items: center; padding: 32px; }
.panel { width: min(760px, 100%); }
.eyebrow { color: #6ee7b7; font-size: 12px; font-weight: 800; text-transform: uppercase; }
h1 { margin: 0; font-size: clamp(40px, 8vw, 84px); line-height: 0.95; }
h2 { margin: 0; font-size: 24px; }
h3 { margin: 0 0 6px; font-size: 14px; color: #eef3f8; }
p { color: #a9b6c5; font-size: 18px; line-height: 1.55; }
a { color: #6ee7b7; font-weight: 700; }
.readiness-panel { width: min(760px, 100%); border: 1px solid #2b3542; border-radius: 8px; padding: 20px; background: #111821; }
.readiness-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 12px; margin-top: 16px; }
.readiness-grid article { border: 1px solid #26313d; border-radius: 8px; padding: 12px; background: #0d1117; }
.readiness-grid p, .readiness-note { margin: 0; font-size: 14px; }
.readiness-note { margin-top: 14px; color: #d4dde8; }
CSS

cat > "$APP_DEST/.gitignore" <<'EOF'
node_modules
.next
.env
tmp/pids
log
EOF

cat > "$APP_DEST/AGENTS.md" <<'MD'
# RDS Next.js Build Notes

- Keep this as a Next.js App Router project.
- Preserve `/api/health`; RDS uses it for local and public health checks.
- Prefer server components by default; use `"use client"` only for interactive components.
- Generated product work should replace the starter UI, not the stack plumbing.
- Preserve and update `components/review-readiness.tsx` until the product has a
  better app-visible truthfulness surface. It must say what works, what is
  seeded/sample, what is stubbed or credential-gated, what is missing, and how
  review credentials work.
MD
