#!/usr/bin/env bash
set -euo pipefail

APP_NAME="${1:-rds_extension}"
APP_DEST="${2:?app destination required}"

slug="$(printf '%s' "$APP_NAME" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g')"
[[ -n "$slug" ]] || slug="rds-extension"

mkdir -p "$APP_DEST/entrypoints/background" "$APP_DEST/entrypoints/content" "$APP_DEST/entrypoints/popup" "$APP_DEST/entrypoints/options" "$APP_DEST/components" "$APP_DEST/utils" "$APP_DEST/public" "$APP_DEST/preview" "$APP_DEST/tests/unit" "$APP_DEST/tmp/pids" "$APP_DEST/log"

cat > "$APP_DEST/package.json" <<JSON
{
  "name": "${slug}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "wxt",
    "build:extension": "wxt build",
    "zip": "wxt zip",
    "package": "bun run zip || true; node scripts/normalize-zip.mjs",
    "test": "bun run build:extension"
  },
  "dependencies": {
    "@types/bun": "latest",
    "@types/chrome": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@vitejs/plugin-react": "latest",
    "react": "latest",
    "react-dom": "latest",
    "typescript": "latest",
    "wxt": "latest"
  },
  "devDependencies": {}
}
JSON

cat > "$APP_DEST/wxt.config.ts" <<'TS'
import { defineConfig } from "wxt";

export default defineConfig({
  manifest: {
    name: "RDS Extension",
    description: "Browser extension generated by RDS.",
    permissions: ["storage", "activeTab"],
    host_permissions: [],
    action: {
      default_title: "RDS Extension",
    },
  },
});
TS

cat > "$APP_DEST/tsconfig.json" <<'JSON'
{
  "extends": "./.wxt/tsconfig.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "strict": true,
    "types": ["chrome", "bun-types"]
  }
}
JSON

cat > "$APP_DEST/entrypoints/background.ts" <<'TS'
export default defineBackground(() => {
  chrome.runtime.onInstalled.addListener(() => {
    chrome.storage.local.set({ installedAt: new Date().toISOString() });
  });
});
TS

cat > "$APP_DEST/entrypoints/content.ts" <<'TS'
export default defineContentScript({
  matches: ["<all_urls>"],
  main() {
    document.documentElement.dataset.rdsExtensionLoaded = "true";
  },
});
TS

cat > "$APP_DEST/entrypoints/popup/index.html" <<'HTML'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RDS Extension</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./main.tsx"></script>
  </body>
</html>
HTML

cat > "$APP_DEST/entrypoints/popup/main.tsx" <<'TSX'
import React from "react";
import ReactDOM from "react-dom/client";
import "./style.css";

function Popup() {
  return (
    <main>
      <p className="eyebrow">RDS browser-extension stack</p>
      <h1>Extension shell ready</h1>
      <p>Popup, background worker, content script, storage, and zip packaging are wired.</p>
      <button type="button" onClick={() => chrome?.tabs?.query?.({ active: true, currentWindow: true })}>
        Check active tab
      </button>
    </main>
  );
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <Popup />
  </React.StrictMode>,
);
TSX

cat > "$APP_DEST/entrypoints/popup/style.css" <<'CSS'
:root {
  color: #172033;
  background: #f8fafc;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
* { box-sizing: border-box; }
body { margin: 0; min-width: 320px; }
main { width: 360px; max-width: 100vw; padding: 18px; }
.eyebrow { color: #0f766e; font-size: 11px; font-weight: 800; text-transform: uppercase; }
h1 { margin: 0; font-size: 26px; line-height: 1; }
p { color: #475569; line-height: 1.45; }
button {
  width: 100%;
  min-height: 40px;
  border: 1px solid #0f766e;
  background: #0f766e;
  color: #fff;
  font-weight: 800;
  cursor: pointer;
}
CSS

cat > "$APP_DEST/entrypoints/options/index.html" <<'HTML'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RDS Extension Options</title>
  </head>
  <body>
    <main>
      <h1>Options</h1>
      <p>Configure extension settings here.</p>
    </main>
  </body>
</html>
HTML

cat > "$APP_DEST/preview/index.html" <<'HTML'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RDS Extension Preview</title>
    <style>
      :root { color: #172033; background: #eef2f7; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
      body { margin: 0; min-width: 320px; min-height: 100vh; display: grid; place-items: center; padding: 24px; }
      iframe { width: 390px; height: 300px; border: 1px solid #cbd5e1; background: #fff; }
      section { display: grid; gap: 12px; }
      a { color: #0f766e; font-weight: 800; }
    </style>
  </head>
  <body>
    <section>
      <article>
        <p class="eyebrow">RDS browser-extension stack</p>
        <h1>Extension shell ready</h1>
        <p>Popup, background worker, content script, storage, and zip packaging are wired.</p>
        <button type="button">Check active tab</button>
      </article>
      <a href="/extension.zip">Download extension zip</a>
    </section>
  </body>
</html>
HTML

cat > "$APP_DEST/preview-server.ts" <<'TS'
import { existsSync } from "node:fs";
import { join } from "node:path";

const port = Number(process.env.HOST_PORT || process.env.PORT || 4000);
const root = process.cwd();

function fileFor(pathname: string) {
  if (pathname === "/") return join(root, "preview/index.html");
  if (pathname === "/health.json") return join(root, "health.json");
  if (pathname === "/extension.zip") return join(root, ".output/rds-extension.zip");
  return join(root, pathname.replace(/^\//, ""));
}

function typeFor(pathname: string) {
  if (pathname.endsWith(".html")) return "text/html; charset=utf-8";
  if (pathname.endsWith(".css")) return "text/css; charset=utf-8";
  if (pathname.endsWith(".js") || pathname.endsWith(".tsx") || pathname.endsWith(".ts")) return "text/javascript; charset=utf-8";
  if (pathname.endsWith(".json")) return "application/json; charset=utf-8";
  if (pathname.endsWith(".zip")) return "application/zip";
  return "application/octet-stream";
}

Bun.serve({
  port,
  async fetch(req) {
    const url = new URL(req.url);
    const path = fileFor(url.pathname);
    if (!existsSync(path)) return new Response("Not found", { status: 404 });
    return new Response(Bun.file(path), { headers: { "content-type": typeFor(url.pathname) } });
  },
});

console.log(`extension preview listening on ${port}`);
TS

mkdir -p "$APP_DEST/scripts"
cat > "$APP_DEST/scripts/normalize-zip.mjs" <<'JS'
import { copyFileSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

mkdirSync(".output", { recursive: true });
const zips = readdirSync(".output").filter((file) => file.endsWith(".zip"));
if (zips.length > 0) {
  copyFileSync(join(".output", zips[0]), ".output/rds-extension.zip");
  console.log("normalized .output/rds-extension.zip");
} else {
  writeFileSync(".output/rds-extension.zip", "WXT zip failed; inspect .output/chrome-mv3 and run wxt zip locally.\n");
  console.log("wrote fallback .output/rds-extension.zip");
}
JS

cat > "$APP_DEST/health.json" <<'JSON'
{"ok":true,"stack":"browser-extension"}
JSON

cat > "$APP_DEST/.gitignore" <<'EOF'
node_modules
.wxt
.output
.env
tmp/pids
log
EOF

if [[ ! -f "$APP_DEST/.env" ]]; then
  : > "$APP_DEST/.env"
fi

cat > "$APP_DEST/AGENTS.md" <<'MD'
# RDS Browser Extension Build Notes

- Keep this as a WXT MV3 extension.
- Preserve `/health.json` and the Zo popup preview at `/`.
- Keep permissions minimal. Prefer `activeTab` and explicit host permissions only when the PRD requires them.
- Build output must include `.output/chrome-mv3` and a zip artifact for side-loading.
MD

echo "Initialized browser-extension app at $APP_DEST"
