#!/usr/bin/env bash
set -euo pipefail

APP_NAME="${1:-rds_python_ai_service}"
APP_DEST="${2:?app destination required}"

slug="$(printf '%s' "$APP_NAME" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g')"
[[ -n "$slug" ]] || slug="rds-python-ai-service"

mkdir -p "$APP_DEST/app/routers" "$APP_DEST/agents" "$APP_DEST/prompts" "$APP_DEST/tests" "$APP_DEST/tmp/pids" "$APP_DEST/log"

cat > "$APP_DEST/pyproject.toml" <<TOML
[project]
name = "${slug}"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.32",
  "pydantic>=2.9",
  "pydantic-settings>=2.6",
  "httpx>=0.28"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
TOML

cat > "$APP_DEST/requirements.txt" <<'REQ'
fastapi>=0.115
uvicorn[standard]>=0.32
pydantic>=2.9
pydantic-settings>=2.6
pytest>=8.3
httpx>=0.28
REQ

cat > "$APP_DEST/app/__init__.py" <<'PY'
PY

cat > "$APP_DEST/app/main.py" <<'PY'
from fastapi import FastAPI
from fastapi.responses import HTMLResponse, RedirectResponse
from pydantic import BaseModel

app = FastAPI(
    title="RDS Python AI Service",
    version="0.1.0",
    description="FastAPI starter generated by RDS.",
)


class AgentRequest(BaseModel):
    input: str


class AgentResponse(BaseModel):
    output: str
    stack: str = "python-ai-service"


@app.get("/", include_in_schema=False)
async def root() -> HTMLResponse:
    return HTMLResponse(
        """
        <!doctype html>
        <html lang="en">
          <head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RDS Python AI Service</title></head>
          <body style="font-family: system-ui; margin: 48px; max-width: 760px;">
            <p style="font-size:12px;font-weight:800;text-transform:uppercase;color:#2563eb;">RDS Python AI service</p>
            <h1>Ready for implementation</h1>
            <p>This service exposes <a href="/docs">interactive API docs</a> and a JSON health check.</p>
          </body>
        </html>
        """
    )


@app.get("/health")
async def health() -> dict[str, bool | str]:
    return {"ok": True, "stack": "python-ai-service"}


@app.get("/docs-link", include_in_schema=False)
async def docs_link() -> RedirectResponse:
    return RedirectResponse("/docs")


@app.post("/agent", response_model=AgentResponse)
async def agent(request: AgentRequest) -> AgentResponse:
    return AgentResponse(output=f"Received: {request.input}")
PY

cat > "$APP_DEST/tests/test_health.py" <<'PY'
from fastapi.testclient import TestClient

from app.main import app


def test_health():
    client = TestClient(app)
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["ok"] is True
PY

cat > "$APP_DEST/.gitignore" <<'EOF'
.venv
__pycache__
.pytest_cache
.env
tmp/pids
log
EOF

cat > "$APP_DEST/AGENTS.md" <<'MD'
# RDS Python AI Service Build Notes

- Keep this as a FastAPI service.
- Preserve `/health`; RDS uses it for local and public health checks.
- Root should remain browser-usable and `/docs` should remain available.
- External provider keys must be optional unless the PRD explicitly requires them.
MD
